Room.create(:room_id => "1", :name => "Forest", :description => "You are in a dark forest.")
Room.create(:room_id => "2", :name => "Hills", :description => "You are among the hills.")
Room.create(:room_id => "3", :name => "Desert", :description => "You are in the desert.  It is hot!")
Room.create(:room_id => "4", :name => "East Sea", :description => "You are in the east sea.")
Room.create(:room_id => "5", :name => "West Sea", :description => "You are in the west sea.")

Exit.create(:exit_id => "1", :name => "North path", :description => "The hills are to the north", :transition_msg => "You go north.", :command => "n", :origin_id => "1", :destination_id => "2")
Exit.create(:exit_id => "2", :name => "South path", :description => "The desert is to the south", :transition_msg => "You go south.", :command => "s", :origin_id => "1", :destination_id => "3")
Exit.create(:exit_id => "3", :name => "West path", :description => "The sea is to the west", :transition_msg => "You go west.", :command => "w", :origin_id => "1", :destination_id => "5")
Exit.create(:exit_id => "4", :name => "East path", :description => "The sea is to the east", :transition_msg => "You go east.", :command => "e", :origin_id => "1", :destination_id => "4")
Exit.create(:exit_id => "5", :name => "Forest path", :description => "The forest is to the south", :transition_msg => "You go south.", :command => "s", :origin_id => "2", :destination_id => "1")
Exit.create(:exit_id => "6", :name => "Forest path", :description => "The forest is to the north", :transition_msg => "You go north.", :command => "n", :origin_id => "3", :destination_id => "1")
Exit.create(:exit_id => "7", :name => "Forest path", :description => "The forest is to the east", :transition_msg => "You go east.", :command => "e", :origin_id => "5", :destination_id => "1")
Exit.create(:exit_id => "1", :name => "Forest path", :description => "The forest is to the west", :transition_msg => "You go west.", :command => "w", :origin_id => "4", :destination_id => "1")
